### ISSUE TITLE
ICM: Provide a capability to download heapdumps after crash of icm-as containers 

### ISSUE THREAD

**Issue by csperrhake** [intershop/helm-charts#141]

**Comment by csperrhake** [comment]
https://danlebrero.com/2018/11/20/how-to-do-java-jvm-heapdump-in-kubernetes/

**Comment by DevDavido** [comment]
It's possible to create heap dumps on OutOfMemory since at least ICM-AS Helm Chart v0.2.6 by setting the env `ENABLE_HEAPDUMP` for the icm-as pod to `true`. Dumps will be written to configured directory of `$IS_DUMPS` (current default value `/intershop/sites/root/log/dumps`) then.

ICM-AS Helm Chart values:
```yaml
# [...]
environment:
  ENABLE_HEAPDUMP: true
# [...]
```
