### ISSUE TITLE
ICM: Support JVM memory configuration

### ISSUE THREAD

**Issue by skiesewetter-intershop** [intershop/helm-charts#165]

**Comment by A-Herold** [comment]
Just a hint how we solved this problem. We have splitted the Java options in to two parameters in response to  request from Ops.

Parameter|Description|Default Value
---|---|---
jboss.javaOpts | The value of jboss.javaOpts is passed to Java options of the WildFly application server.The default value used by Helm charts 1.5.0 and newer allows for not having to care about Java memory settings any longer. Just set the memory size in parameter resources and the JVM will recognize this and adapt its memory configuration to this value. | `-XX:+UseContainerSupport -XX:MinRAMPercentage=85 -XX:MaxRAMPercentage=85`
jboss.javaOptsAppend | Java options, to be passed to the application-server, are built from the two parameters jboss.javaOpts and jboss.javaOptsAppend. It is recommended to not overwrite jboss.javaOpts or only to overwrite it, if really necessary. This way the maintenance effort of your values-file will be reduced, since it's not necessary to track changes of the default value of jboss.javaOpts, that have to be reapplied to the overwritten value. |

**Comment by khauser** [comment]
@A-Herold: 
* `UseContainerSupport` is set by default and so not needed
* We should set -XX:MaxRAMPercentage (would be like setting xmx but through container limit&requests) and -XX:InitialRAMPercentage (like xms)
* MinRAMPercentage is not what you think it is
* 85% is too high since 15% are not only for the OS. There should be also space for Java native memory or non-heap. I would start with 65% and then monitor the memory consumption and maybe adjust later.

**Comment by skiesewetter-intershop** [comment]
Discusses target solution:

- use the 2 variables `jvm.options` and `jvm.optionsAppend` with a default value of "-XX:MinRAMPercentage=85 -XX:MaxRAMPercentage=85" for `jvm.options`
- actual java options are built from `jvm.options` + `jvm.optionsAppend`
- set resources.requests = resources.limits

**Comment by khauser** [comment]
> The MinRAMPercentage parameter, unlike its name, allows setting the maximum heap size for a JVM running with a small amount of memory (less than 200MB).

We do have much more than 200MB and for that reason are using `XX:MaxRAMPercentage`. The name of the parameter is leading in the wrong direction. Instead you need `XX:InitialRAMPercentage=85`, which indirectly determines xms.
